name: Build all apps.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout RInChI.
    - uses: actions/checkout@v2

    - name: Build RInChI command-line utility.
      run: cd RInChI/src/example_apps/rinchi_cmdline/; make -f Makefile-64bit

    - name: Build RInChI - "Reaction from molfiles" example app.
      run: cd RInChI/src/example_apps/rxn_from_molfiles/ ; make -f Makefile-64bit

    - name: Build RInChI - "C API usage" example app.
      run: cd RInChI/src/example_apps/c_api_usage/ ; make -f Makefile-64bit
