name: Run test suite.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies.
      run: sudo apt-get update && sudo apt-get install -yq libboost-dev libboost-system-dev libboost-filesystem-dev

    - name: Build and run test suite.
      run: cd src/test/test_suite ; make -f Makefile-64bit DEFINES+=-DSKIP_MOLFILE_READER_INCHI_REGRESS_TEST ; cd .. ; ./test_suite/rinchi_test_suite
